#
# Copyright (c) 2025 Composiv.ai
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Composiv.ai - initial API and implementation
#

pipelines:
  - name: start
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_provision
          plugin: ProvisionPlugin
          name: provision_step
          condition: "should_run_provision == True"
        - service: muto_start_stack
          plugin: LaunchPlugin
          name: start_stack_step
          condition: "compose_step.success == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin
  - name: kill
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_kill_stack
          plugin: LaunchPlugin
          name: kill_stack_step
          condition: "should_run_launch == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin 
  - name: apply
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_provision
          plugin: ProvisionPlugin
          name: provision_step
          condition: "should_run_provision == True"
        - service: muto_apply_stack
          plugin: LaunchPlugin
          name: apply_stack_step
          condition: "compose_step.success == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin
