name: Colcon Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          mkdir -p $(pwd)/tmp/muto/src/
          ln -s $(pwd) $(pwd)/tmp/muto/src/composer
          cd $(pwd)/tmp/muto
          . /opt/ros/humble/setup.sh
          apt-get update -y
          apt-get install python3-pip -y
          rosdep update
          rosdep install --from-path src --ignore-src -r -y --rosdistro humble
          colcon build
          . install/setup.bash
          colcon test
          colcon test-result --all --verbose
        name: Build in ros2 container
